import Head from 'next/head'
import Header from '../src/components/Header'
import Footer from '../src/components/Footer'
import Content from '../src/components/Content'
import type { NextPage } from 'next'

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Content />
      <Footer />
    </div>
  )
}

export default Home
